# Generated by Django 4.2.23 on 2025-07-11 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('pendente', 'Pendente'), ('em_atendimento', 'Em Atendimento')], default='aberto', max_length=20, verbose_name='Status')),
                ('canal', models.CharField(default='whatsapp', max_length=50, verbose_name='Canal')),
                ('last_message_at', models.DateTimeField(auto_now_add=True, verbose_name='Última Mensagem em')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usuario', verbose_name='Atendente')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('wapi_instance_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Instância W-APi')),
                ('wapi_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token W-APi')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID do Evento')),
                ('instance_id', models.CharField(max_length=255, verbose_name='ID da Instância')),
                ('event_type', models.CharField(max_length=255, verbose_name='Tipo do Evento')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsappInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Instância W-APi')),
                ('token', models.CharField(max_length=255, verbose_name='Token da Instância')),
                ('status', models.CharField(choices=[('conectado', 'Conectado'), ('desconectado', 'Desconectado'), ('pendente', 'Pendente'), ('qrcode_gerado', 'QR Code Gerado'), ('erro', 'Erro')], default='pendente', max_length=50, verbose_name='Status da Conexão')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='QR Code')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Última Vez Online')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente', verbose_name='Cliente Associado')),
            ],
            options={
                'verbose_name': 'Instância do WhatsApp',
                'verbose_name_plural': 'Instâncias do WhatsApp',
                'ordering': ['instance_id'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=255, verbose_name='Remetente')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('documento', 'Documento'), ('sticker', 'Sticker'), ('localizacao', 'Localização'), ('contato', 'Contato'), ('desconhecido', 'Desconhecido')], default='texto', max_length=50, verbose_name='Tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chat', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['data_envio'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Departamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
                'unique_together': {('nome', 'cliente')},
            },
        ),
    ]
