# Generated by Django 4.2.23 on 2025-07-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status da Instância'),
        ),
    ]
