# Generated by Django 4.2.23 on 2025-07-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='status',
        ),
    ]
