# Generated by Django 4.2.15 on 2025-07-17 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_cliente_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={
                "ordering": ["-last_message_at", "-data_inicio"],
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
            },
        ),
        migrations.AlterModelOptions(
            name="whatsappinstance",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Instância do WhatsApp",
                "verbose_name_plural": "Instâncias do WhatsApp",
            },
        ),
        migrations.AddField(
            model_name="chat",
            name="chat_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID do Chat"
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="canal",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("instagram", "Instagram"),
                ],
                default="whatsapp",
                max_length=20,
                verbose_name="Canal",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="core.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="last_message_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última Mensagem"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("closed", "Fechado"),
                    ("pending", "Pendente"),
                ],
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="empresa",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Empresa"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departamentos",
                to="core.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="nome",
            field=models.CharField(max_length=255, verbose_name="Nome do Departamento"),
        ),
        migrations.AlterField(
            model_name="mensagem",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mensagens",
                to="core.chat",
                verbose_name="Chat",
            ),
        ),
        migrations.AlterField(
            model_name="mensagem",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("image", "Imagem"),
                    ("video", "Vídeo"),
                    ("audio", "Áudio"),
                    ("document", "Documento"),
                    ("sticker", "Sticker"),
                    ("location", "Localização"),
                    ("contact", "Contato"),
                    ("poll", "Enquete"),
                ],
                default="text",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="event_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="ID do Evento"
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="event_type",
            field=models.CharField(max_length=100, verbose_name="Tipo do Evento"),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="payload",
            field=models.JSONField(verbose_name="Payload do Evento"),
        ),
        migrations.AlterField(
            model_name="whatsappinstance",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_instances",
                to="core.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinstance",
            name="instance_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="ID da Instância"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinstance",
            name="status",
            field=models.CharField(
                default="disconnected", max_length=50, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappinstance",
            name="token",
            field=models.CharField(max_length=255, verbose_name="Token de Acesso"),
        ),
        migrations.AlterField(
            model_name="whatsappinstance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("chat_id", "cliente")},
        ),
    ]
