# Generated by Django 4.2.23 on 2025-07-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chat_options_alter_whatsappinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Chat'),
        ),
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='É Grupo'),
        ),
    ]
