# Generated by Django 4.2.23 on 2025-07-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chat_chat_name_chat_is_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.URLField(blank=True, null=True, verbose_name='Foto de Perfil'),
        ),
    ]
