# Generated by Django 4.2.23 on 2025-07-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='from_me',
            field=models.BooleanField(default=False, verbose_name='Enviada por Mim'),
        ),
    ]
