# Generated by Django 4.2.23 on 2025-07-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mensagem_from_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='foto_perfil',
            field=models.URLField(blank=True, null=True, verbose_name='Foto de Perfil'),
        ),
    ]
