# Generated by Django 4.2.23 on 2025-07-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chat_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID da Mensagem WhatsApp'),
        ),
    ]
