# Generated by Django 4.2.15 on 2025-07-19 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_mensagem_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="ID da Mensagem WhatsApp",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=255, verbose_name="Nome do Remetente"),
                ),
                (
                    "sender_id",
                    models.CharField(max_length=255, verbose_name="ID do Remetente"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Imagem"),
                            ("video", "Vídeo"),
                            ("audio", "Áudio"),
                            ("document", "Documento"),
                            ("sticker", "Sticker"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Mídia",
                    ),
                ),
                ("mimetype", models.CharField(max_length=100, verbose_name="Mimetype")),
                (
                    "file_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Arquivo",
                    ),
                ),
                (
                    "file_path",
                    models.TextField(
                        blank=True, null=True, verbose_name="Caminho do Arquivo"
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Tamanho do Arquivo (bytes)"
                    ),
                ),
                (
                    "caption",
                    models.TextField(blank=True, null=True, verbose_name="Legenda"),
                ),
                (
                    "width",
                    models.IntegerField(blank=True, null=True, verbose_name="Largura"),
                ),
                (
                    "height",
                    models.IntegerField(blank=True, null=True, verbose_name="Altura"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duração (segundos)"
                    ),
                ),
                (
                    "is_ptt",
                    models.BooleanField(default=False, verbose_name="Push to Talk"),
                ),
                (
                    "download_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("success", "Baixado"),
                            ("failed", "Falhou"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status do Download",
                    ),
                ),
                (
                    "is_group",
                    models.BooleanField(default=False, verbose_name="É Grupo"),
                ),
                (
                    "from_me",
                    models.BooleanField(default=False, verbose_name="Enviada por Mim"),
                ),
                (
                    "media_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chave de Mídia",
                    ),
                ),
                (
                    "direct_path",
                    models.TextField(
                        blank=True, null=True, verbose_name="Caminho Direto"
                    ),
                ),
                (
                    "file_sha256",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SHA256 do Arquivo",
                    ),
                ),
                (
                    "file_enc_sha256",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SHA256 Enc do Arquivo",
                    ),
                ),
                (
                    "media_key_timestamp",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Timestamp da Chave",
                    ),
                ),
                (
                    "message_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Timestamp da Mensagem"
                    ),
                ),
                (
                    "download_timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Timestamp do Download"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="core.chat",
                        verbose_name="Chat",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="core.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="core.whatsappinstance",
                        verbose_name="Instância",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo de Mídia",
                "verbose_name_plural": "Arquivos de Mídia",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cliente", "instance"],
                        name="core_mediaf_cliente_7440ba_idx",
                    ),
                    models.Index(
                        fields=["message_id"], name="core_mediaf_message_ae8f01_idx"
                    ),
                    models.Index(
                        fields=["media_type", "download_status"],
                        name="core_mediaf_media_t_2ef73c_idx",
                    ),
                    models.Index(
                        fields=["sender_id", "chat"],
                        name="core_mediaf_sender__a7c80e_idx",
                    ),
                ],
            },
        ),
    ]
