# Generated by Django 4.2.15 on 2025-07-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_mediafile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="group_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID Único do Grupo",
            ),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="sender_display_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome de Exibição do Remetente",
            ),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="sender_push_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome Push do Remetente",
            ),
        ),
        migrations.AddField(
            model_name="mensagem",
            name="sender_verified_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome Verificado do Remetente",
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["cliente", "chat_id"], name="core_chat_cliente_4655a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["is_group", "group_id"], name="core_chat_is_grou_b63f01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(
                fields=["chat", "data_envio"], name="core_mensag_chat_id_f95c9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(
                fields=["remetente", "from_me"], name="core_mensag_remeten_1dfa29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensagem",
            index=models.Index(
                fields=["chat", "sender_display_name"],
                name="core_mensag_chat_id_c42faf_idx",
            ),
        ),
    ]
