# Generated by Django 4.2.15 on 2025-07-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_chat_group_id_mensagem_sender_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensagem",
            name="reacoes",
            field=models.JSONField(blank=True, default=list, verbose_name="Reações"),
        ),
    ]
