# Generated by Django 4.2.23 on 2025-07-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_corrigir_chat_ids'),
    ]

    operations = [
        # Esta migração adiciona validação automática de chat_id no modelo Chat
        # A função normalize_chat_id() é chamada automaticamente no método save()
        # para garantir que todos os chat_ids sejam números de telefone válidos
        # sem sufixos como @lid, @c.us, etc.
    ]
