# Generated by Django 4.2.15 on 2025-07-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_usuario_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="nome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nome Completo"
            ),
        ),
    ]
