# Generated by Django 4.2.23 on 2025-07-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente'), ('colaborador', 'Colaborador')], default='colaborador', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
