# Generated by Django 4.2.23 on 2025-07-14 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, unique=True, verbose_name='ID do Chat')),
                ('chat_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Chat')),
                ('is_group', models.BooleanField(default=False, verbose_name='É Grupo')),
                ('group_participants', models.JSONField(blank=True, default=list, verbose_name='Participantes do Grupo')),
                ('status', models.CharField(default='active', max_length=50, verbose_name='Status')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Mensagem')),
                ('message_count', models.IntegerField(default=0, verbose_name='Total de Mensagens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_chats', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=255, verbose_name='ID do Remetente')),
                ('push_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome de Exibição')),
                ('verified_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Verificado')),
                ('is_business', models.BooleanField(default=False, verbose_name='É Business')),
                ('business_profile', models.JSONField(blank=True, default=dict, verbose_name='Perfil Business')),
                ('message_count', models.IntegerField(default=0, verbose_name='Total de Mensagens')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Última Vez Online')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_senders', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Remetente',
                'verbose_name_plural': 'Remetentes',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='RealTimeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('active_chats', models.IntegerField(default=0, verbose_name='Chats Ativos')),
                ('pending_messages', models.IntegerField(default=0, verbose_name='Mensagens Pendentes')),
                ('online_users', models.IntegerField(default=0, verbose_name='Usuários Online')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='Tempo Médio de Resposta')),
                ('message_throughput', models.FloatField(default=0, verbose_name='Taxa de Mensagens/min')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_realtime_stats', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Estatística em Tempo Real',
                'verbose_name_plural': 'Estatísticas em Tempo Real',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Total de Mensagens')),
                ('received_messages', models.IntegerField(default=0, verbose_name='Mensagens Recebidas')),
                ('sent_messages', models.IntegerField(default=0, verbose_name='Mensagens Enviadas')),
                ('text_messages', models.IntegerField(default=0, verbose_name='Mensagens de Texto')),
                ('media_messages', models.IntegerField(default=0, verbose_name='Mensagens de Mídia')),
                ('document_messages', models.IntegerField(default=0, verbose_name='Mensagens de Documento')),
                ('delivered_messages', models.IntegerField(default=0, verbose_name='Mensagens Entregues')),
                ('read_messages', models.IntegerField(default=0, verbose_name='Mensagens Lidas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_message_stats', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Estatística de Mensagem',
                'verbose_name_plural': 'Estatísticas de Mensagens',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Mensagem')),
                ('message_type', models.CharField(max_length=50, verbose_name='Tipo da Mensagem')),
                ('content', models.JSONField(verbose_name='Conteúdo')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Texto da Mensagem')),
                ('from_me', models.BooleanField(default=False, verbose_name='Enviada por Mim')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('status', models.CharField(default='sent', max_length=50, verbose_name='Status')),
                ('media_url', models.URLField(blank=True, null=True, verbose_name='URL da Mídia')),
                ('media_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo da Mídia')),
                ('media_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho da Mídia')),
                ('reactions', models.JSONField(blank=True, default=list, verbose_name='Reações')),
                ('quoted_message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensagem Citada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.chat', verbose_name='Chat')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_messages', to='core.cliente', verbose_name='Cliente')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.sender', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContactStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('message_count', models.IntegerField(default=0, verbose_name='Total de Mensagens')),
                ('first_message_at', models.DateTimeField(verbose_name='Primeira Mensagem')),
                ('last_message_at', models.DateTimeField(verbose_name='Última Mensagem')),
                ('avg_response_time', models.FloatField(blank=True, null=True, verbose_name='Tempo Médio de Resposta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_contact_stats', to='core.cliente', verbose_name='Cliente')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.sender', verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Estatística de Contato',
                'verbose_name_plural': 'Estatísticas de Contatos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(max_length=255, verbose_name='ID da Instância')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo do Evento')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('raw_data', models.JSONField(verbose_name='Dados Brutos')),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Chat')),
                ('sender_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Remetente')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Remetente')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da Mensagem')),
                ('message_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo da Mensagem')),
                ('message_content', models.TextField(blank=True, null=True, verbose_name='Conteúdo da Mensagem')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cliente', 'timestamp'], name='webhook_web_cliente_ffda45_idx'), models.Index(fields=['event_type', 'processed'], name='webhook_web_event_t_c622de_idx'), models.Index(fields=['chat_id', 'sender_id'], name='webhook_web_chat_id_6b8394_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sender',
            index=models.Index(fields=['cliente', 'sender_id'], name='webhook_sen_cliente_c8b7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='sender',
            index=models.Index(fields=['is_business', 'last_seen'], name='webhook_sen_is_busi_75ffe0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sender',
            unique_together={('sender_id', 'cliente')},
        ),
        migrations.AddIndex(
            model_name='realtimestats',
            index=models.Index(fields=['cliente', 'timestamp'], name='webhook_rea_cliente_4faa40_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestats',
            index=models.Index(fields=['cliente', 'date'], name='webhook_mes_cliente_4cb158_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestats',
            unique_together={('cliente', 'date')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['cliente', 'chat', 'timestamp'], name='webhook_mes_cliente_bce63e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'from_me'], name='webhook_mes_sender__cb6acf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'status'], name='webhook_mes_message_256135_idx'),
        ),
        migrations.AddIndex(
            model_name='contactstats',
            index=models.Index(fields=['cliente', 'sender', 'date'], name='webhook_con_cliente_f8f466_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactstats',
            unique_together={('cliente', 'sender', 'date')},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['cliente', 'chat_id'], name='webhook_cha_cliente_504f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['status', 'last_message_at'], name='webhook_cha_status_c5a837_idx'),
        ),
    ]
