# Generated by Django 4.2.23 on 2025-07-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='message',
            name='direct_path',
            field=models.TextField(blank=True, null=True, verbose_name='Caminho Direto da Mídia'),
        ),
        migrations.AddField(
            model_name='message',
            name='document_file_length',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho do Documento'),
        ),
        migrations.AddField(
            model_name='message',
            name='document_filename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Documento'),
        ),
        migrations.AddField(
            model_name='message',
            name='document_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mimetype do Documento'),
        ),
        migrations.AddField(
            model_name='message',
            name='document_page_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Páginas do Documento'),
        ),
        migrations.AddField(
            model_name='message',
            name='document_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Documento'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_sha256',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SHA256 do Arquivo'),
        ),
        migrations.AddField(
            model_name='message',
            name='jpeg_thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='Thumbnail JPEG (base64)'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço do Local'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='message',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Local'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_caption',
            field=models.TextField(blank=True, null=True, verbose_name='Legenda da Mídia'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura da Mídia'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave de Mídia'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_key_timestamp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Timestamp da Chave de Mídia'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Largura da Mídia'),
        ),
        migrations.AddField(
            model_name='message',
            name='poll_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Enquete'),
        ),
        migrations.AddField(
            model_name='message',
            name='poll_options',
            field=models.TextField(blank=True, null=True, verbose_name='Opções da Enquete (JSON)'),
        ),
        migrations.AddField(
            model_name='message',
            name='poll_selectable_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd Selecionável'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker_file_length',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho do Sticker'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker_is_ai',
            field=models.BooleanField(default=False, verbose_name='Sticker AI'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker_is_animated',
            field=models.BooleanField(default=False, verbose_name='Sticker Animado'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker_is_avatar',
            field=models.BooleanField(default=False, verbose_name='Sticker Avatar'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker_is_lottie',
            field=models.BooleanField(default=False, verbose_name='Sticker Lottie'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker_mimetype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mimetype do Sticker'),
        ),
        migrations.AddField(
            model_name='message',
            name='sticker_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do Sticker'),
        ),
        migrations.AddField(
            model_name='message',
            name='thumbnail_direct_path',
            field=models.TextField(blank=True, null=True, verbose_name='Caminho Direto do Thumbnail'),
        ),
        migrations.AddField(
            model_name='message',
            name='thumbnail_enc_sha256',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SHA256 Enc do Thumbnail'),
        ),
        migrations.AddField(
            model_name='message',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura do Thumbnail'),
        ),
        migrations.AddField(
            model_name='message',
            name='thumbnail_sha256',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SHA256 do Thumbnail'),
        ),
        migrations.AddField(
            model_name='message',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Largura do Thumbnail'),
        ),
        migrations.AddField(
            model_name='sender',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_path', models.TextField(verbose_name='Caminho do Arquivo de Mídia')),
                ('media_type', models.CharField(max_length=50, verbose_name='Tipo da Mídia')),
                ('mimetype', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mimetype')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo')),
                ('download_status', models.CharField(default='pending', max_length=20, verbose_name='Status do Download')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_medias', to='webhook.webhookevent', verbose_name='Evento de Webhook')),
            ],
            options={
                'verbose_name': 'Mídia de Mensagem',
                'verbose_name_plural': 'Mídias de Mensagem',
                'ordering': ['-created_at'],
            },
        ),
    ]
