# Generated by Django 4.2.15 on 2025-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhook", "0002_chat_profile_picture_message_direct_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="group_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID Único do Grupo",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_display_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome de Exibição do Remetente",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_push_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome Push do Remetente",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_verified_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nome Verificado do Remetente",
            ),
        ),
        migrations.AddIndex(
            model_name="chat",
            index=models.Index(
                fields=["is_group", "group_id"], name="webhook_cha_is_grou_170f7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["chat", "sender_display_name"],
                name="webhook_mes_chat_id_c6784c_idx",
            ),
        ),
    ]
