# Generated by Django 4.2.15 on 2025-07-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webhook", "0003_chat_group_id_message_sender_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemedia",
            name="caption",
            field=models.TextField(blank=True, null=True, verbose_name="Legenda"),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="direct_path",
            field=models.TextField(
                blank=True, null=True, verbose_name="Caminho Direto da Mídia"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="document_filename",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Nome do Documento"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="document_page_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Páginas do Documento"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="document_title",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Título do Documento",
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="download_timestamp",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Timestamp do Download"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="duration_seconds",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Duração (segundos)"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="error_message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mensagem de Erro"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="file_enc_sha256",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="SHA256 Enc do Arquivo",
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="file_sha256",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="SHA256 do Arquivo"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="height",
            field=models.IntegerField(blank=True, null=True, verbose_name="Altura"),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="is_ptt",
            field=models.BooleanField(default=False, verbose_name="Push to Talk"),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="jpeg_thumbnail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Thumbnail JPEG (base64)"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="media_key",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Chave de Mídia"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="media_key_timestamp",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Timestamp da Chave de Mídia",
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="retry_count",
            field=models.IntegerField(default=0, verbose_name="Tentativas de Download"),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="sticker_is_ai",
            field=models.BooleanField(default=False, verbose_name="Sticker AI"),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="sticker_is_animated",
            field=models.BooleanField(default=False, verbose_name="Sticker Animado"),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="sticker_is_avatar",
            field=models.BooleanField(default=False, verbose_name="Sticker Avatar"),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="sticker_is_lottie",
            field=models.BooleanField(default=False, verbose_name="Sticker Lottie"),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="thumbnail_direct_path",
            field=models.TextField(
                blank=True, null=True, verbose_name="Caminho Direto do Thumbnail"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="thumbnail_enc_sha256",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="SHA256 Enc do Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="thumbnail_height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Altura do Thumbnail"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="thumbnail_sha256",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="SHA256 do Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="thumbnail_width",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Largura do Thumbnail"
            ),
        ),
        migrations.AddField(
            model_name="messagemedia",
            name="width",
            field=models.IntegerField(blank=True, null=True, verbose_name="Largura"),
        ),
        migrations.AddIndex(
            model_name="messagemedia",
            index=models.Index(
                fields=["event", "media_type"], name="webhook_mes_event_i_3a58d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagemedia",
            index=models.Index(
                fields=["download_status"], name="webhook_mes_downloa_7db880_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagemedia",
            index=models.Index(
                fields=["media_key"], name="webhook_mes_media_k_473ddd_idx"
            ),
        ),
    ]
